name: Publish Types
on:
  workflow_dispatch:
    inputs:
      spec-version:
        type: boolean
        description: Use and write the version specified in the API spec file
        default: true
      publish-npm:
        type: boolean
        description: Publish to NPM
        default: true
  workflow_call:
    inputs:
      spec-version:
        type: boolean
        description: Use and write the version specified in the API spec file
        default: true
      publish-npm:
        type: boolean
        description: Publish to NPM
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - run: bun install --frozen-lockfile
      
      - run: bun run generate-types
      
      - name: get version
        id: version
        uses: kekedaine/github-action-json-property-by-lodash@0.2.0
        if: ${{ inputs.spec-version }}
        with:
          path: dist/openapi.json
          prop_path: "info.version"

      - name: Write spec version to package.json
        uses: jaywcjlove/github-action-package@v2.0.0
        if: ${{ inputs.spec-version }}
        with:
          version: ${{steps.version.outputs.prop}}

      - run: |
          bun install
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -a -m 'ci: version bump to ${{steps.version.outputs.prop}}'
          git push
        if: ${{ inputs.spec-version }}

      - run: bun publish
        if: ${{ inputs.publish-npm }}
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
